fix: the app was locked too often
ForkbombEu/wallet pull request #416
Opened 2024-07-12 11:45 UTC by phoebus-84

2024-07-12 12:00 UTC, puria requested changes

2024-07-12 12:00 UTC, puria commented on src/routes/+page.ts
> +	redirect(303, r('/unlock', lang));
👌

2024-07-12 12:30 UTC, phoebus-84 commented on src/routes/[[lang]]/(protected)/+layout.svelte
> +			console.log(state)
ups..

2024-07-13 09:06 UTC, puria approved these changes

2024-07-13 09:06 UTC, merged